/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const deleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidPathParamsSchema = z.object({
    "slug": z.string(),
"companyId": z.uuid(),
"employeeId": z.uuid()
    })

/**
 * @description Default Response
 */
export const deleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeid204Schema = z.enum([]).nullable()

export const deleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidMutationResponseSchema = z.lazy(() => deleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeid204Schema)