/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const patchOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidPathParamsSchema = z.object({
    "slug": z.string(),
"companyId": z.uuid(),
"employeeId": z.uuid()
    })

/**
 * @description Default Response
 */
export const patchOrganizationsSlugCompaniesCompanyidEmployeesEmployeeid204Schema = z.enum([]).nullable()

export const patchOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidMutationRequestSchema = z.object({
    "name": z.string(),
"department": z.string()
    })

export const patchOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidMutationResponseSchema = z.lazy(() => patchOrganizationsSlugCompaniesCompanyidEmployeesEmployeeid204Schema)