/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const patchOrganizationsSlugCompaniesCompanyidPathParamsSchema = z.object({
    "slug": z.string(),
"companyId": z.uuid()
    })

/**
 * @description Default Response
 */
export const patchOrganizationsSlugCompaniesCompanyid204Schema = z.enum([]).nullable()

export const patchOrganizationsSlugCompaniesCompanyidMutationRequestSchema = z.object({
    "name": z.string()
    })

export const patchOrganizationsSlugCompaniesCompanyidMutationResponseSchema = z.lazy(() => patchOrganizationsSlugCompaniesCompanyid204Schema)