/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Default Response
 */
export const postOrganizations201Schema = z.object({
    "organizationId": z.uuid()
    })

export const postOrganizationsMutationRequestSchema = z.object({
    "name": z.string(),
"domain": z.string().nullish(),
"shouldAttachUserByDomain": z.optional(z.boolean())
    })

export const postOrganizationsMutationResponseSchema = z.lazy(() => postOrganizations201Schema)