/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const postOrganizationsSlugCompaniesCompanyidEmployeesPathParamsSchema = z.object({
    "slug": z.string(),
"companyId": z.uuid()
    })

/**
 * @description Default Response
 */
export const postOrganizationsSlugCompaniesCompanyidEmployees201Schema = z.object({
    "employeeId": z.uuid()
    })

export const postOrganizationsSlugCompaniesCompanyidEmployeesMutationRequestSchema = z.object({
    "name": z.string(),
"department": z.string()
    })

export const postOrganizationsSlugCompaniesCompanyidEmployeesMutationResponseSchema = z.lazy(() => postOrganizationsSlugCompaniesCompanyidEmployees201Schema)