/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const putOrganizationSlugPathParamsSchema = z.object({
    "slug": z.string()
    })

/**
 * @description Default Response
 */
export const putOrganizationSlug204Schema = z.enum([]).nullable()

export const putOrganizationSlugMutationRequestSchema = z.object({
    "name": z.string(),
"domain": z.string().nullish(),
"shouldAttachUserByDomain": z.optional(z.boolean())
    })

export const putOrganizationSlugMutationResponseSchema = z.lazy(() => putOrganizationSlug204Schema)