/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthLayoutRouteImport } from './pages/_auth/layout'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as AuthVerifyOtpRouteImport } from './pages/_auth/verify-otp'
import { Route as AuthSignOutRouteImport } from './pages/_auth/sign-out'
import { Route as AuthSignInRouteImport } from './pages/_auth/sign-in'
import { Route as AuthInviteLayoutRouteImport } from './pages/_auth/invite/layout'
import { Route as AppSettingsLayoutRouteImport } from './pages/_app/settings/layout'
import { Route as AuthInviteIndexRouteImport } from './pages/_auth/invite/index'
import { Route as AppTransactionsIndexRouteImport } from './pages/_app/transactions/index'
import { Route as AppSettingsIndexRouteImport } from './pages/_app/settings/index'
import { Route as AppSalesIndexRouteImport } from './pages/_app/sales/index'
import { Route as AppProfileIndexRouteImport } from './pages/_app/profile/index'
import { Route as AppCommissionsIndexRouteImport } from './pages/_app/commissions/index'
import { Route as AppDashboardIndexRouteImport } from './pages/_app/_dashboard/index'
import { Route as AuthPasswordResetRouteImport } from './pages/_auth/password/reset'
import { Route as AuthPasswordRecoverRouteImport } from './pages/_auth/password/recover'
import { Route as AuthPasswordForgotRouteImport } from './pages/_auth/password/forgot'
import { Route as AuthGoogleCallbackRouteImport } from './pages/_auth/google/callback'
import { Route as AppSalesCreateRouteImport } from './pages/_app/sales/create'
import { Route as AppSalesSaleIdRouteImport } from './pages/_app/sales/$saleId'
import { Route as AuthInviteInviteIdIndexRouteImport } from './pages/_auth/invite/$inviteId/index'
import { Route as AppTransactionsCreateIndexRouteImport } from './pages/_app/transactions/create/index'
import { Route as AppSettingsOrganizationIndexRouteImport } from './pages/_app/settings/organization/index'
import { Route as AppSettingsMembersIndexRouteImport } from './pages/_app/settings/members/index'
import { Route as AppRegistersSellersIndexRouteImport } from './pages/_app/registers/sellers/index'
import { Route as AppRegistersProductsIndexRouteImport } from './pages/_app/registers/products/index'
import { Route as AppRegistersPartnersIndexRouteImport } from './pages/_app/registers/partners/index'
import { Route as AppRegistersEmployeesIndexRouteImport } from './pages/_app/registers/employees/index'
import { Route as AppRegistersCustomersIndexRouteImport } from './pages/_app/registers/customers/index'
import { Route as AppRegistersCostCentersIndexRouteImport } from './pages/_app/registers/cost-centers/index'
import { Route as AppRegistersCompaniesIndexRouteImport } from './pages/_app/registers/companies/index'
import { Route as AppRegistersCategoriesIndexRouteImport } from './pages/_app/registers/categories/index'
import { Route as AuthInviteInviteIdAcceptRouteImport } from './pages/_auth/invite/$inviteId/accept'
import { Route as AppTransactionsUpdateTransactionIdRouteImport } from './pages/_app/transactions/update/$transactionId'
import { Route as AppSalesUpdateSaleIdRouteImport } from './pages/_app/sales/update/$saleId'
import { Route as AppRegistersSellersUpdateRouteImport } from './pages/_app/registers/sellers/update'
import { Route as AppRegistersSellersCreateRouteImport } from './pages/_app/registers/sellers/create'
import { Route as AppRegistersPartnersUpdateRouteImport } from './pages/_app/registers/partners/update'
import { Route as AppRegistersPartnersCreateRouteImport } from './pages/_app/registers/partners/create'
import { Route as AppRegistersCustomersUpdateRouteImport } from './pages/_app/registers/customers/update'
import { Route as AppRegistersCustomersCreateRouteImport } from './pages/_app/registers/customers/create'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthInviteLayoutRoute = AuthInviteLayoutRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppSettingsLayoutRoute = AppSettingsLayoutRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthInviteIndexRoute = AuthInviteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthInviteLayoutRoute,
} as any)
const AppTransactionsIndexRoute = AppTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsLayoutRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppCommissionsIndexRoute = AppCommissionsIndexRouteImport.update({
  id: '/commissions/',
  path: '/commissions/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/_dashboard/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthPasswordResetRoute = AuthPasswordResetRouteImport.update({
  id: '/password/reset',
  path: '/password/reset',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthPasswordRecoverRoute = AuthPasswordRecoverRouteImport.update({
  id: '/password/recover',
  path: '/password/recover',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthPasswordForgotRoute = AuthPasswordForgotRouteImport.update({
  id: '/password/forgot',
  path: '/password/forgot',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/google/callback',
  path: '/google/callback',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppSalesCreateRoute = AppSalesCreateRouteImport.update({
  id: '/sales/create',
  path: '/sales/create',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppSalesSaleIdRoute = AppSalesSaleIdRouteImport.update({
  id: '/sales/$saleId',
  path: '/sales/$saleId',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthInviteInviteIdIndexRoute = AuthInviteInviteIdIndexRouteImport.update({
  id: '/$inviteId/',
  path: '/$inviteId/',
  getParentRoute: () => AuthInviteLayoutRoute,
} as any)
const AppTransactionsCreateIndexRoute =
  AppTransactionsCreateIndexRouteImport.update({
    id: '/transactions/create/',
    path: '/transactions/create/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppSettingsOrganizationIndexRoute =
  AppSettingsOrganizationIndexRouteImport.update({
    id: '/organization/',
    path: '/organization/',
    getParentRoute: () => AppSettingsLayoutRoute,
  } as any)
const AppSettingsMembersIndexRoute = AppSettingsMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => AppSettingsLayoutRoute,
} as any)
const AppRegistersSellersIndexRoute =
  AppRegistersSellersIndexRouteImport.update({
    id: '/registers/sellers/',
    path: '/registers/sellers/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistersProductsIndexRoute =
  AppRegistersProductsIndexRouteImport.update({
    id: '/registers/products/',
    path: '/registers/products/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistersPartnersIndexRoute =
  AppRegistersPartnersIndexRouteImport.update({
    id: '/registers/partners/',
    path: '/registers/partners/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistersEmployeesIndexRoute =
  AppRegistersEmployeesIndexRouteImport.update({
    id: '/registers/employees/',
    path: '/registers/employees/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistersCustomersIndexRoute =
  AppRegistersCustomersIndexRouteImport.update({
    id: '/registers/customers/',
    path: '/registers/customers/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistersCostCentersIndexRoute =
  AppRegistersCostCentersIndexRouteImport.update({
    id: '/registers/cost-centers/',
    path: '/registers/cost-centers/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistersCompaniesIndexRoute =
  AppRegistersCompaniesIndexRouteImport.update({
    id: '/registers/companies/',
    path: '/registers/companies/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistersCategoriesIndexRoute =
  AppRegistersCategoriesIndexRouteImport.update({
    id: '/registers/categories/',
    path: '/registers/categories/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AuthInviteInviteIdAcceptRoute =
  AuthInviteInviteIdAcceptRouteImport.update({
    id: '/$inviteId/accept',
    path: '/$inviteId/accept',
    getParentRoute: () => AuthInviteLayoutRoute,
  } as any)
const AppTransactionsUpdateTransactionIdRoute =
  AppTransactionsUpdateTransactionIdRouteImport.update({
    id: '/transactions/update/$transactionId',
    path: '/transactions/update/$transactionId',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppSalesUpdateSaleIdRoute = AppSalesUpdateSaleIdRouteImport.update({
  id: '/sales/update/$saleId',
  path: '/sales/update/$saleId',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppRegistersSellersUpdateRoute =
  AppRegistersSellersUpdateRouteImport.update({
    id: '/registers/sellers/update',
    path: '/registers/sellers/update',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistersSellersCreateRoute =
  AppRegistersSellersCreateRouteImport.update({
    id: '/registers/sellers/create',
    path: '/registers/sellers/create',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistersPartnersUpdateRoute =
  AppRegistersPartnersUpdateRouteImport.update({
    id: '/registers/partners/update',
    path: '/registers/partners/update',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistersPartnersCreateRoute =
  AppRegistersPartnersCreateRouteImport.update({
    id: '/registers/partners/create',
    path: '/registers/partners/create',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistersCustomersUpdateRoute =
  AppRegistersCustomersUpdateRouteImport.update({
    id: '/registers/customers/update',
    path: '/registers/customers/update',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistersCustomersCreateRoute =
  AppRegistersCustomersCreateRouteImport.update({
    id: '/registers/customers/create',
    path: '/registers/customers/create',
    getParentRoute: () => AppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/settings': typeof AppSettingsLayoutRouteWithChildren
  '/invite': typeof AuthInviteLayoutRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/sign-out': typeof AuthSignOutRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/sales/$saleId': typeof AppSalesSaleIdRoute
  '/sales/create': typeof AppSalesCreateRoute
  '/google/callback': typeof AuthGoogleCallbackRoute
  '/password/forgot': typeof AuthPasswordForgotRoute
  '/password/recover': typeof AuthPasswordRecoverRoute
  '/password/reset': typeof AuthPasswordResetRoute
  '/': typeof AppDashboardIndexRoute
  '/commissions': typeof AppCommissionsIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/sales': typeof AppSalesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/transactions': typeof AppTransactionsIndexRoute
  '/invite/': typeof AuthInviteIndexRoute
  '/registers/customers/create': typeof AppRegistersCustomersCreateRoute
  '/registers/customers/update': typeof AppRegistersCustomersUpdateRoute
  '/registers/partners/create': typeof AppRegistersPartnersCreateRoute
  '/registers/partners/update': typeof AppRegistersPartnersUpdateRoute
  '/registers/sellers/create': typeof AppRegistersSellersCreateRoute
  '/registers/sellers/update': typeof AppRegistersSellersUpdateRoute
  '/sales/update/$saleId': typeof AppSalesUpdateSaleIdRoute
  '/transactions/update/$transactionId': typeof AppTransactionsUpdateTransactionIdRoute
  '/invite/$inviteId/accept': typeof AuthInviteInviteIdAcceptRoute
  '/registers/categories': typeof AppRegistersCategoriesIndexRoute
  '/registers/companies': typeof AppRegistersCompaniesIndexRoute
  '/registers/cost-centers': typeof AppRegistersCostCentersIndexRoute
  '/registers/customers': typeof AppRegistersCustomersIndexRoute
  '/registers/employees': typeof AppRegistersEmployeesIndexRoute
  '/registers/partners': typeof AppRegistersPartnersIndexRoute
  '/registers/products': typeof AppRegistersProductsIndexRoute
  '/registers/sellers': typeof AppRegistersSellersIndexRoute
  '/settings/members': typeof AppSettingsMembersIndexRoute
  '/settings/organization': typeof AppSettingsOrganizationIndexRoute
  '/transactions/create': typeof AppTransactionsCreateIndexRoute
  '/invite/$inviteId': typeof AuthInviteInviteIdIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof AuthSignInRoute
  '/sign-out': typeof AuthSignOutRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/sales/$saleId': typeof AppSalesSaleIdRoute
  '/sales/create': typeof AppSalesCreateRoute
  '/google/callback': typeof AuthGoogleCallbackRoute
  '/password/forgot': typeof AuthPasswordForgotRoute
  '/password/recover': typeof AuthPasswordRecoverRoute
  '/password/reset': typeof AuthPasswordResetRoute
  '/': typeof AppDashboardIndexRoute
  '/commissions': typeof AppCommissionsIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/sales': typeof AppSalesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/transactions': typeof AppTransactionsIndexRoute
  '/invite': typeof AuthInviteIndexRoute
  '/registers/customers/create': typeof AppRegistersCustomersCreateRoute
  '/registers/customers/update': typeof AppRegistersCustomersUpdateRoute
  '/registers/partners/create': typeof AppRegistersPartnersCreateRoute
  '/registers/partners/update': typeof AppRegistersPartnersUpdateRoute
  '/registers/sellers/create': typeof AppRegistersSellersCreateRoute
  '/registers/sellers/update': typeof AppRegistersSellersUpdateRoute
  '/sales/update/$saleId': typeof AppSalesUpdateSaleIdRoute
  '/transactions/update/$transactionId': typeof AppTransactionsUpdateTransactionIdRoute
  '/invite/$inviteId/accept': typeof AuthInviteInviteIdAcceptRoute
  '/registers/categories': typeof AppRegistersCategoriesIndexRoute
  '/registers/companies': typeof AppRegistersCompaniesIndexRoute
  '/registers/cost-centers': typeof AppRegistersCostCentersIndexRoute
  '/registers/customers': typeof AppRegistersCustomersIndexRoute
  '/registers/employees': typeof AppRegistersEmployeesIndexRoute
  '/registers/partners': typeof AppRegistersPartnersIndexRoute
  '/registers/products': typeof AppRegistersProductsIndexRoute
  '/registers/sellers': typeof AppRegistersSellersIndexRoute
  '/settings/members': typeof AppSettingsMembersIndexRoute
  '/settings/organization': typeof AppSettingsOrganizationIndexRoute
  '/transactions/create': typeof AppTransactionsCreateIndexRoute
  '/invite/$inviteId': typeof AuthInviteInviteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_app/settings': typeof AppSettingsLayoutRouteWithChildren
  '/_auth/invite': typeof AuthInviteLayoutRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-out': typeof AuthSignOutRoute
  '/_auth/verify-otp': typeof AuthVerifyOtpRoute
  '/_app/sales/$saleId': typeof AppSalesSaleIdRoute
  '/_app/sales/create': typeof AppSalesCreateRoute
  '/_auth/google/callback': typeof AuthGoogleCallbackRoute
  '/_auth/password/forgot': typeof AuthPasswordForgotRoute
  '/_auth/password/recover': typeof AuthPasswordRecoverRoute
  '/_auth/password/reset': typeof AuthPasswordResetRoute
  '/_app/_dashboard/': typeof AppDashboardIndexRoute
  '/_app/commissions/': typeof AppCommissionsIndexRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_app/sales/': typeof AppSalesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/transactions/': typeof AppTransactionsIndexRoute
  '/_auth/invite/': typeof AuthInviteIndexRoute
  '/_app/registers/customers/create': typeof AppRegistersCustomersCreateRoute
  '/_app/registers/customers/update': typeof AppRegistersCustomersUpdateRoute
  '/_app/registers/partners/create': typeof AppRegistersPartnersCreateRoute
  '/_app/registers/partners/update': typeof AppRegistersPartnersUpdateRoute
  '/_app/registers/sellers/create': typeof AppRegistersSellersCreateRoute
  '/_app/registers/sellers/update': typeof AppRegistersSellersUpdateRoute
  '/_app/sales/update/$saleId': typeof AppSalesUpdateSaleIdRoute
  '/_app/transactions/update/$transactionId': typeof AppTransactionsUpdateTransactionIdRoute
  '/_auth/invite/$inviteId/accept': typeof AuthInviteInviteIdAcceptRoute
  '/_app/registers/categories/': typeof AppRegistersCategoriesIndexRoute
  '/_app/registers/companies/': typeof AppRegistersCompaniesIndexRoute
  '/_app/registers/cost-centers/': typeof AppRegistersCostCentersIndexRoute
  '/_app/registers/customers/': typeof AppRegistersCustomersIndexRoute
  '/_app/registers/employees/': typeof AppRegistersEmployeesIndexRoute
  '/_app/registers/partners/': typeof AppRegistersPartnersIndexRoute
  '/_app/registers/products/': typeof AppRegistersProductsIndexRoute
  '/_app/registers/sellers/': typeof AppRegistersSellersIndexRoute
  '/_app/settings/members/': typeof AppSettingsMembersIndexRoute
  '/_app/settings/organization/': typeof AppSettingsOrganizationIndexRoute
  '/_app/transactions/create/': typeof AppTransactionsCreateIndexRoute
  '/_auth/invite/$inviteId/': typeof AuthInviteInviteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/invite'
    | '/sign-in'
    | '/sign-out'
    | '/verify-otp'
    | '/sales/$saleId'
    | '/sales/create'
    | '/google/callback'
    | '/password/forgot'
    | '/password/recover'
    | '/password/reset'
    | '/'
    | '/commissions'
    | '/profile'
    | '/sales'
    | '/settings/'
    | '/transactions'
    | '/invite/'
    | '/registers/customers/create'
    | '/registers/customers/update'
    | '/registers/partners/create'
    | '/registers/partners/update'
    | '/registers/sellers/create'
    | '/registers/sellers/update'
    | '/sales/update/$saleId'
    | '/transactions/update/$transactionId'
    | '/invite/$inviteId/accept'
    | '/registers/categories'
    | '/registers/companies'
    | '/registers/cost-centers'
    | '/registers/customers'
    | '/registers/employees'
    | '/registers/partners'
    | '/registers/products'
    | '/registers/sellers'
    | '/settings/members'
    | '/settings/organization'
    | '/transactions/create'
    | '/invite/$inviteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-out'
    | '/verify-otp'
    | '/sales/$saleId'
    | '/sales/create'
    | '/google/callback'
    | '/password/forgot'
    | '/password/recover'
    | '/password/reset'
    | '/'
    | '/commissions'
    | '/profile'
    | '/sales'
    | '/settings'
    | '/transactions'
    | '/invite'
    | '/registers/customers/create'
    | '/registers/customers/update'
    | '/registers/partners/create'
    | '/registers/partners/update'
    | '/registers/sellers/create'
    | '/registers/sellers/update'
    | '/sales/update/$saleId'
    | '/transactions/update/$transactionId'
    | '/invite/$inviteId/accept'
    | '/registers/categories'
    | '/registers/companies'
    | '/registers/cost-centers'
    | '/registers/customers'
    | '/registers/employees'
    | '/registers/partners'
    | '/registers/products'
    | '/registers/sellers'
    | '/settings/members'
    | '/settings/organization'
    | '/transactions/create'
    | '/invite/$inviteId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/settings'
    | '/_auth/invite'
    | '/_auth/sign-in'
    | '/_auth/sign-out'
    | '/_auth/verify-otp'
    | '/_app/sales/$saleId'
    | '/_app/sales/create'
    | '/_auth/google/callback'
    | '/_auth/password/forgot'
    | '/_auth/password/recover'
    | '/_auth/password/reset'
    | '/_app/_dashboard/'
    | '/_app/commissions/'
    | '/_app/profile/'
    | '/_app/sales/'
    | '/_app/settings/'
    | '/_app/transactions/'
    | '/_auth/invite/'
    | '/_app/registers/customers/create'
    | '/_app/registers/customers/update'
    | '/_app/registers/partners/create'
    | '/_app/registers/partners/update'
    | '/_app/registers/sellers/create'
    | '/_app/registers/sellers/update'
    | '/_app/sales/update/$saleId'
    | '/_app/transactions/update/$transactionId'
    | '/_auth/invite/$inviteId/accept'
    | '/_app/registers/categories/'
    | '/_app/registers/companies/'
    | '/_app/registers/cost-centers/'
    | '/_app/registers/customers/'
    | '/_app/registers/employees/'
    | '/_app/registers/partners/'
    | '/_app/registers/products/'
    | '/_app/registers/sellers/'
    | '/_app/settings/members/'
    | '/_app/settings/organization/'
    | '/_app/transactions/create/'
    | '/_auth/invite/$inviteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verify-otp': {
      id: '/_auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/sign-out': {
      id: '/_auth/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof AuthSignOutRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/invite': {
      id: '/_auth/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AuthInviteLayoutRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsLayoutRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_auth/invite/': {
      id: '/_auth/invite/'
      path: '/'
      fullPath: '/invite/'
      preLoaderRoute: typeof AuthInviteIndexRouteImport
      parentRoute: typeof AuthInviteLayoutRoute
    }
    '/_app/transactions/': {
      id: '/_app/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsLayoutRoute
    }
    '/_app/sales/': {
      id: '/_app/sales/'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/commissions/': {
      id: '/_app/commissions/'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof AppCommissionsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_dashboard/': {
      id: '/_app/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_auth/password/reset': {
      id: '/_auth/password/reset'
      path: '/password/reset'
      fullPath: '/password/reset'
      preLoaderRoute: typeof AuthPasswordResetRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/password/recover': {
      id: '/_auth/password/recover'
      path: '/password/recover'
      fullPath: '/password/recover'
      preLoaderRoute: typeof AuthPasswordRecoverRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/password/forgot': {
      id: '/_auth/password/forgot'
      path: '/password/forgot'
      fullPath: '/password/forgot'
      preLoaderRoute: typeof AuthPasswordForgotRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/google/callback': {
      id: '/_auth/google/callback'
      path: '/google/callback'
      fullPath: '/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/sales/create': {
      id: '/_app/sales/create'
      path: '/sales/create'
      fullPath: '/sales/create'
      preLoaderRoute: typeof AppSalesCreateRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/sales/$saleId': {
      id: '/_app/sales/$saleId'
      path: '/sales/$saleId'
      fullPath: '/sales/$saleId'
      preLoaderRoute: typeof AppSalesSaleIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_auth/invite/$inviteId/': {
      id: '/_auth/invite/$inviteId/'
      path: '/$inviteId'
      fullPath: '/invite/$inviteId'
      preLoaderRoute: typeof AuthInviteInviteIdIndexRouteImport
      parentRoute: typeof AuthInviteLayoutRoute
    }
    '/_app/transactions/create/': {
      id: '/_app/transactions/create/'
      path: '/transactions/create'
      fullPath: '/transactions/create'
      preLoaderRoute: typeof AppTransactionsCreateIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/settings/organization/': {
      id: '/_app/settings/organization/'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AppSettingsOrganizationIndexRouteImport
      parentRoute: typeof AppSettingsLayoutRoute
    }
    '/_app/settings/members/': {
      id: '/_app/settings/members/'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AppSettingsMembersIndexRouteImport
      parentRoute: typeof AppSettingsLayoutRoute
    }
    '/_app/registers/sellers/': {
      id: '/_app/registers/sellers/'
      path: '/registers/sellers'
      fullPath: '/registers/sellers'
      preLoaderRoute: typeof AppRegistersSellersIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registers/products/': {
      id: '/_app/registers/products/'
      path: '/registers/products'
      fullPath: '/registers/products'
      preLoaderRoute: typeof AppRegistersProductsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registers/partners/': {
      id: '/_app/registers/partners/'
      path: '/registers/partners'
      fullPath: '/registers/partners'
      preLoaderRoute: typeof AppRegistersPartnersIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registers/employees/': {
      id: '/_app/registers/employees/'
      path: '/registers/employees'
      fullPath: '/registers/employees'
      preLoaderRoute: typeof AppRegistersEmployeesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registers/customers/': {
      id: '/_app/registers/customers/'
      path: '/registers/customers'
      fullPath: '/registers/customers'
      preLoaderRoute: typeof AppRegistersCustomersIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registers/cost-centers/': {
      id: '/_app/registers/cost-centers/'
      path: '/registers/cost-centers'
      fullPath: '/registers/cost-centers'
      preLoaderRoute: typeof AppRegistersCostCentersIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registers/companies/': {
      id: '/_app/registers/companies/'
      path: '/registers/companies'
      fullPath: '/registers/companies'
      preLoaderRoute: typeof AppRegistersCompaniesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registers/categories/': {
      id: '/_app/registers/categories/'
      path: '/registers/categories'
      fullPath: '/registers/categories'
      preLoaderRoute: typeof AppRegistersCategoriesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_auth/invite/$inviteId/accept': {
      id: '/_auth/invite/$inviteId/accept'
      path: '/$inviteId/accept'
      fullPath: '/invite/$inviteId/accept'
      preLoaderRoute: typeof AuthInviteInviteIdAcceptRouteImport
      parentRoute: typeof AuthInviteLayoutRoute
    }
    '/_app/transactions/update/$transactionId': {
      id: '/_app/transactions/update/$transactionId'
      path: '/transactions/update/$transactionId'
      fullPath: '/transactions/update/$transactionId'
      preLoaderRoute: typeof AppTransactionsUpdateTransactionIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/sales/update/$saleId': {
      id: '/_app/sales/update/$saleId'
      path: '/sales/update/$saleId'
      fullPath: '/sales/update/$saleId'
      preLoaderRoute: typeof AppSalesUpdateSaleIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registers/sellers/update': {
      id: '/_app/registers/sellers/update'
      path: '/registers/sellers/update'
      fullPath: '/registers/sellers/update'
      preLoaderRoute: typeof AppRegistersSellersUpdateRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registers/sellers/create': {
      id: '/_app/registers/sellers/create'
      path: '/registers/sellers/create'
      fullPath: '/registers/sellers/create'
      preLoaderRoute: typeof AppRegistersSellersCreateRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registers/partners/update': {
      id: '/_app/registers/partners/update'
      path: '/registers/partners/update'
      fullPath: '/registers/partners/update'
      preLoaderRoute: typeof AppRegistersPartnersUpdateRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registers/partners/create': {
      id: '/_app/registers/partners/create'
      path: '/registers/partners/create'
      fullPath: '/registers/partners/create'
      preLoaderRoute: typeof AppRegistersPartnersCreateRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registers/customers/update': {
      id: '/_app/registers/customers/update'
      path: '/registers/customers/update'
      fullPath: '/registers/customers/update'
      preLoaderRoute: typeof AppRegistersCustomersUpdateRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registers/customers/create': {
      id: '/_app/registers/customers/create'
      path: '/registers/customers/create'
      fullPath: '/registers/customers/create'
      preLoaderRoute: typeof AppRegistersCustomersCreateRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppSettingsLayoutRouteChildren {
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSettingsMembersIndexRoute: typeof AppSettingsMembersIndexRoute
  AppSettingsOrganizationIndexRoute: typeof AppSettingsOrganizationIndexRoute
}

const AppSettingsLayoutRouteChildren: AppSettingsLayoutRouteChildren = {
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSettingsMembersIndexRoute: AppSettingsMembersIndexRoute,
  AppSettingsOrganizationIndexRoute: AppSettingsOrganizationIndexRoute,
}

const AppSettingsLayoutRouteWithChildren =
  AppSettingsLayoutRoute._addFileChildren(AppSettingsLayoutRouteChildren)

interface AppLayoutRouteChildren {
  AppSettingsLayoutRoute: typeof AppSettingsLayoutRouteWithChildren
  AppSalesSaleIdRoute: typeof AppSalesSaleIdRoute
  AppSalesCreateRoute: typeof AppSalesCreateRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppCommissionsIndexRoute: typeof AppCommissionsIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppSalesIndexRoute: typeof AppSalesIndexRoute
  AppTransactionsIndexRoute: typeof AppTransactionsIndexRoute
  AppRegistersCustomersCreateRoute: typeof AppRegistersCustomersCreateRoute
  AppRegistersCustomersUpdateRoute: typeof AppRegistersCustomersUpdateRoute
  AppRegistersPartnersCreateRoute: typeof AppRegistersPartnersCreateRoute
  AppRegistersPartnersUpdateRoute: typeof AppRegistersPartnersUpdateRoute
  AppRegistersSellersCreateRoute: typeof AppRegistersSellersCreateRoute
  AppRegistersSellersUpdateRoute: typeof AppRegistersSellersUpdateRoute
  AppSalesUpdateSaleIdRoute: typeof AppSalesUpdateSaleIdRoute
  AppTransactionsUpdateTransactionIdRoute: typeof AppTransactionsUpdateTransactionIdRoute
  AppRegistersCategoriesIndexRoute: typeof AppRegistersCategoriesIndexRoute
  AppRegistersCompaniesIndexRoute: typeof AppRegistersCompaniesIndexRoute
  AppRegistersCostCentersIndexRoute: typeof AppRegistersCostCentersIndexRoute
  AppRegistersCustomersIndexRoute: typeof AppRegistersCustomersIndexRoute
  AppRegistersEmployeesIndexRoute: typeof AppRegistersEmployeesIndexRoute
  AppRegistersPartnersIndexRoute: typeof AppRegistersPartnersIndexRoute
  AppRegistersProductsIndexRoute: typeof AppRegistersProductsIndexRoute
  AppRegistersSellersIndexRoute: typeof AppRegistersSellersIndexRoute
  AppTransactionsCreateIndexRoute: typeof AppTransactionsCreateIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppSettingsLayoutRoute: AppSettingsLayoutRouteWithChildren,
  AppSalesSaleIdRoute: AppSalesSaleIdRoute,
  AppSalesCreateRoute: AppSalesCreateRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppCommissionsIndexRoute: AppCommissionsIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppSalesIndexRoute: AppSalesIndexRoute,
  AppTransactionsIndexRoute: AppTransactionsIndexRoute,
  AppRegistersCustomersCreateRoute: AppRegistersCustomersCreateRoute,
  AppRegistersCustomersUpdateRoute: AppRegistersCustomersUpdateRoute,
  AppRegistersPartnersCreateRoute: AppRegistersPartnersCreateRoute,
  AppRegistersPartnersUpdateRoute: AppRegistersPartnersUpdateRoute,
  AppRegistersSellersCreateRoute: AppRegistersSellersCreateRoute,
  AppRegistersSellersUpdateRoute: AppRegistersSellersUpdateRoute,
  AppSalesUpdateSaleIdRoute: AppSalesUpdateSaleIdRoute,
  AppTransactionsUpdateTransactionIdRoute:
    AppTransactionsUpdateTransactionIdRoute,
  AppRegistersCategoriesIndexRoute: AppRegistersCategoriesIndexRoute,
  AppRegistersCompaniesIndexRoute: AppRegistersCompaniesIndexRoute,
  AppRegistersCostCentersIndexRoute: AppRegistersCostCentersIndexRoute,
  AppRegistersCustomersIndexRoute: AppRegistersCustomersIndexRoute,
  AppRegistersEmployeesIndexRoute: AppRegistersEmployeesIndexRoute,
  AppRegistersPartnersIndexRoute: AppRegistersPartnersIndexRoute,
  AppRegistersProductsIndexRoute: AppRegistersProductsIndexRoute,
  AppRegistersSellersIndexRoute: AppRegistersSellersIndexRoute,
  AppTransactionsCreateIndexRoute: AppTransactionsCreateIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AuthInviteLayoutRouteChildren {
  AuthInviteIndexRoute: typeof AuthInviteIndexRoute
  AuthInviteInviteIdAcceptRoute: typeof AuthInviteInviteIdAcceptRoute
  AuthInviteInviteIdIndexRoute: typeof AuthInviteInviteIdIndexRoute
}

const AuthInviteLayoutRouteChildren: AuthInviteLayoutRouteChildren = {
  AuthInviteIndexRoute: AuthInviteIndexRoute,
  AuthInviteInviteIdAcceptRoute: AuthInviteInviteIdAcceptRoute,
  AuthInviteInviteIdIndexRoute: AuthInviteInviteIdIndexRoute,
}

const AuthInviteLayoutRouteWithChildren =
  AuthInviteLayoutRoute._addFileChildren(AuthInviteLayoutRouteChildren)

interface AuthLayoutRouteChildren {
  AuthInviteLayoutRoute: typeof AuthInviteLayoutRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignOutRoute: typeof AuthSignOutRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  AuthPasswordForgotRoute: typeof AuthPasswordForgotRoute
  AuthPasswordRecoverRoute: typeof AuthPasswordRecoverRoute
  AuthPasswordResetRoute: typeof AuthPasswordResetRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthInviteLayoutRoute: AuthInviteLayoutRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignOutRoute: AuthSignOutRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  AuthPasswordForgotRoute: AuthPasswordForgotRoute,
  AuthPasswordRecoverRoute: AuthPasswordRecoverRoute,
  AuthPasswordResetRoute: AuthPasswordResetRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
