ALTER TYPE "SaleResponsibleType" ADD VALUE IF NOT EXISTS 'COMPANY';
ALTER TYPE "SaleResponsibleType" ADD VALUE IF NOT EXISTS 'UNIT';
ALTER TYPE "SaleResponsibleType" ADD VALUE IF NOT EXISTS 'SUPERVISOR';
ALTER TYPE "SaleResponsibleType" ADD VALUE IF NOT EXISTS 'OTHER';

ALTER TABLE "sales" ADD COLUMN IF NOT EXISTS "responsible_label" TEXT;
