export const PERMISSION_CATALOG = [
	{
		key: "sales.view",
		module: "sales",
		action: "view",
		description: "Visualizar vendas e detalhes.",
	},
	{
		key: "sales.view.all",
		module: "sales",
		action: "view.all",
		description:
			"Visualizar todas as vendas da organização, além das vinculadas ao membro.",
	},
	{
		key: "sales.create",
		module: "sales",
		action: "create",
		description: "Criar vendas.",
	},
	{
		key: "sales.update",
		module: "sales",
		action: "update",
		description: "Editar vendas.",
	},
	{
		key: "sales.status.change",
		module: "sales",
		action: "status.change",
		description: "Alterar status de vendas.",
	},
	{
		key: "sales.delete",
		module: "sales",
		action: "delete",
		description: "Excluir vendas.",
	},
	{
		key: "sales.commissions.manage",
		module: "sales",
		action: "commissions.manage",
		description: "Gerenciar parcelas e status de comissões de vendas.",
	},
	{
		key: "sales.commissions.installments.status.change",
		module: "sales",
		action: "commissions.installments.status.change",
		description: "Alterar status de parcelas de comissão (pagar/cancelar).",
	},
	{
		key: "sales.commissions.installments.update",
		module: "sales",
		action: "commissions.installments.update",
		description: "Editar parcelas de comissão.",
	},
	{
		key: "sales.commissions.installments.delete",
		module: "sales",
		action: "commissions.installments.delete",
		description: "Excluir parcelas de comissão.",
	},
	{
		key: "sales.commissions.view.all",
		module: "sales",
		action: "commissions.view.all",
		description:
			"Visualizar todas as comissões da organização, além das vinculadas ao membro.",
	},
	{
		key: "sales.import.manage",
		module: "sales",
		action: "import.manage",
		description: "Gerenciar importações e templates de vendas.",
	},
	{
		key: "sales.dashboard.view",
		module: "sales",
		action: "dashboard.view",
		description: "Visualizar indicadores de vendas.",
	},
	{
		key: "transactions.view",
		module: "transactions",
		action: "view",
		description: "Visualizar transações.",
	},
	{
		key: "transactions.create",
		module: "transactions",
		action: "create",
		description: "Criar transações.",
	},
	{
		key: "transactions.update",
		module: "transactions",
		action: "update",
		description: "Editar transações.",
	},
	{
		key: "transactions.delete",
		module: "transactions",
		action: "delete",
		description: "Excluir transações.",
	},
	{
		key: "transactions.payment.manage",
		module: "transactions",
		action: "payment.manage",
		description: "Realizar baixa/pagamento de transações.",
	},
	{
		key: "transactions.recurrences.view",
		module: "transactions",
		action: "recurrences.view",
		description: "Visualizar recorrências de transações.",
	},
	{
		key: "transactions.recurrences.manage",
		module: "transactions",
		action: "recurrences.manage",
		description: "Gerenciar recorrências de transações.",
	},
	{
		key: "registers.categories.view",
		module: "registers.categories",
		action: "view",
		description: "Visualizar categorias.",
	},
	{
		key: "registers.categories.create",
		module: "registers.categories",
		action: "create",
		description: "Criar categorias.",
	},
	{
		key: "registers.categories.update",
		module: "registers.categories",
		action: "update",
		description: "Editar categorias.",
	},
	{
		key: "registers.categories.delete",
		module: "registers.categories",
		action: "delete",
		description: "Excluir categorias.",
	},
	{
		key: "registers.companies.view",
		module: "registers.companies",
		action: "view",
		description: "Visualizar empresas.",
	},
	{
		key: "registers.companies.create",
		module: "registers.companies",
		action: "create",
		description: "Criar empresas.",
	},
	{
		key: "registers.companies.update",
		module: "registers.companies",
		action: "update",
		description: "Editar empresas e unidades.",
	},
	{
		key: "registers.companies.delete",
		module: "registers.companies",
		action: "delete",
		description: "Excluir empresas e unidades.",
	},
	{
		key: "registers.cost-centers.view",
		module: "registers.cost-centers",
		action: "view",
		description: "Visualizar centros de custo.",
	},
	{
		key: "registers.cost-centers.create",
		module: "registers.cost-centers",
		action: "create",
		description: "Criar centros de custo.",
	},
	{
		key: "registers.cost-centers.update",
		module: "registers.cost-centers",
		action: "update",
		description: "Editar centros de custo.",
	},
	{
		key: "registers.cost-centers.delete",
		module: "registers.cost-centers",
		action: "delete",
		description: "Excluir centros de custo.",
	},
	{
		key: "registers.customers.view",
		module: "registers.customers",
		action: "view",
		description: "Visualizar clientes.",
	},
	{
		key: "registers.customers.view.all",
		module: "registers.customers",
		action: "view.all",
		description:
			"Visualizar todos os clientes da organização, além dos vinculados ao membro.",
	},
	{
		key: "registers.customers.create",
		module: "registers.customers",
		action: "create",
		description: "Criar clientes.",
	},
	{
		key: "registers.customers.update",
		module: "registers.customers",
		action: "update",
		description: "Editar clientes.",
	},
	{
		key: "registers.customers.delete",
		module: "registers.customers",
		action: "delete",
		description: "Excluir clientes.",
	},
	{
		key: "registers.employees.view",
		module: "registers.employees",
		action: "view",
		description: "Visualizar funcionários.",
	},
	{
		key: "registers.employees.create",
		module: "registers.employees",
		action: "create",
		description: "Criar funcionários.",
	},
	{
		key: "registers.employees.update",
		module: "registers.employees",
		action: "update",
		description: "Editar funcionários.",
	},
	{
		key: "registers.employees.delete",
		module: "registers.employees",
		action: "delete",
		description: "Excluir funcionários.",
	},
	{
		key: "registers.partners.view",
		module: "registers.partners",
		action: "view",
		description: "Visualizar apenas parceiros vinculados.",
	},
	{
		key: "registers.partners.view.all",
		module: "registers.partners",
		action: "view.all",
		description:
			"Visualizar todos os parceiros da organização, além dos vinculados ao membro.",
	},
	{
		key: "registers.partners.create",
		module: "registers.partners",
		action: "create",
		description: "Criar parceiros.",
	},
	{
		key: "registers.partners.update",
		module: "registers.partners",
		action: "update",
		description: "Editar parceiros.",
	},
	{
		key: "registers.partners.delete",
		module: "registers.partners",
		action: "delete",
		description: "Excluir parceiros.",
	},
	{
		key: "registers.products.view",
		module: "registers.products",
		action: "view",
		description: "Visualizar produtos.",
	},
	{
		key: "registers.products.create",
		module: "registers.products",
		action: "create",
		description: "Criar produtos.",
	},
	{
		key: "registers.products.update",
		module: "registers.products",
		action: "update",
		description: "Editar produtos.",
	},
	{
		key: "registers.products.delete",
		module: "registers.products",
		action: "delete",
		description: "Excluir produtos.",
	},
	{
		key: "registers.products.commissions.manage",
		module: "registers.products",
		action: "commissions.manage",
		description: "Gerenciar cenários de comissão de produtos.",
	},
	{
		key: "registers.products.fields.manage",
		module: "registers.products",
		action: "fields.manage",
		description: "Gerenciar campos dinâmicos de vendas por produto.",
	},
	{
		key: "registers.sellers.view",
		module: "registers.sellers",
		action: "view",
		description: "Visualizar vendedores.",
	},
	{
		key: "registers.sellers.create",
		module: "registers.sellers",
		action: "create",
		description: "Criar vendedores.",
	},
	{
		key: "registers.sellers.update",
		module: "registers.sellers",
		action: "update",
		description: "Editar vendedores.",
	},
	{
		key: "registers.sellers.delete",
		module: "registers.sellers",
		action: "delete",
		description: "Excluir vendedores.",
	},
	{
		key: "registers.units.view",
		module: "registers.units",
		action: "view",
		description: "Visualizar unidades.",
	},
	{
		key: "registers.units.create",
		module: "registers.units",
		action: "create",
		description: "Criar unidades.",
	},
	{
		key: "registers.units.update",
		module: "registers.units",
		action: "update",
		description: "Editar unidades.",
	},
	{
		key: "registers.units.delete",
		module: "registers.units",
		action: "delete",
		description: "Excluir unidades.",
	},
	{
		key: "settings.organization.view",
		module: "settings.organization",
		action: "view",
		description: "Visualizar configurações de organização.",
	},
	{
		key: "settings.organization.update",
		module: "settings.organization",
		action: "update",
		description: "Editar configurações de organização.",
	},
	{
		key: "settings.members.view",
		module: "settings.members",
		action: "view",
		description: "Visualizar membros da organização.",
	},
	{
		key: "settings.members.manage",
		module: "settings.members",
		action: "manage",
		description: "Gerenciar membros, papéis e escopos.",
	},
	{
		key: "settings.permissions.manage",
		module: "settings.permissions",
		action: "manage",
		description: "Gerenciar presets e overrides de permissões.",
	},
] as const;

export type PermissionCatalogEntry = (typeof PERMISSION_CATALOG)[number];
export type PermissionKey = PermissionCatalogEntry["key"];
export type PermissionCatalogKey = PermissionCatalogEntry["key"];
