/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { DeleteOrganizationSlugMutationResponse, DeleteOrganizationSlugPathParams } from "../types/DeleteOrganizationSlug.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteOrganizationSlugMutationKey = () => [{ url: '/organization/:slug' }] as const

export type DeleteOrganizationSlugMutationKey = ReturnType<typeof deleteOrganizationSlugMutationKey>

/**
 * @summary Shutdown Organization
 * {@link /organization/:slug}
 */
export async function deleteOrganizationSlug({ slug }: { slug: DeleteOrganizationSlugPathParams["slug"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteOrganizationSlugMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : `/organization/${slug}`, ... requestConfig })  
  return res.data
}

export function deleteOrganizationSlugMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = deleteOrganizationSlugMutationKey()
  return mutationOptions<DeleteOrganizationSlugMutationResponse, ResponseErrorConfig<Error>, {slug: DeleteOrganizationSlugPathParams["slug"]}, TContext>({
    mutationKey,
    mutationFn: async({ slug }) => {
      return deleteOrganizationSlug({ slug }, config)
    },
  })
}

/**
 * @summary Shutdown Organization
 * {@link /organization/:slug}
 */
export function useDeleteOrganizationSlug<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteOrganizationSlugMutationResponse, ResponseErrorConfig<Error>, {slug: DeleteOrganizationSlugPathParams["slug"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteOrganizationSlugMutationKey()

  const baseOptions = deleteOrganizationSlugMutationOptions(config) as UseMutationOptions<DeleteOrganizationSlugMutationResponse, ResponseErrorConfig<Error>, {slug: DeleteOrganizationSlugPathParams["slug"]}, TContext>


  return useMutation<DeleteOrganizationSlugMutationResponse, ResponseErrorConfig<Error>, {slug: DeleteOrganizationSlugPathParams["slug"]}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<DeleteOrganizationSlugMutationResponse, ResponseErrorConfig<Error>, {slug: DeleteOrganizationSlugPathParams["slug"]}, TContext>
}