/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidMutationResponse, DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidPathParams } from "../types/DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeid.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidMutationKey = () => [{ url: '/organizations/:slug/companies/:companyId/employees/:employeeId' }] as const

export type DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidMutationKey = ReturnType<typeof deleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidMutationKey>

/**
 * @summary Delete employee
 * {@link /organizations/:slug/companies/:companyId/employees/:employeeId}
 */
export async function deleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeid({ slug, companyId, employeeId }: { slug: DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidPathParams["slug"]; companyId: DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidPathParams["companyId"]; employeeId: DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidPathParams["employeeId"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : `/organizations/${slug}/companies/${companyId}/employees/${employeeId}`, ... requestConfig })  
  return res.data
}

export function deleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = deleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidMutationKey()
  return mutationOptions<DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidMutationResponse, ResponseErrorConfig<Error>, {slug: DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidPathParams["slug"], companyId: DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidPathParams["companyId"], employeeId: DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidPathParams["employeeId"]}, TContext>({
    mutationKey,
    mutationFn: async({ slug, companyId, employeeId }) => {
      return deleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeid({ slug, companyId, employeeId }, config)
    },
  })
}

/**
 * @summary Delete employee
 * {@link /organizations/:slug/companies/:companyId/employees/:employeeId}
 */
export function useDeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeid<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidMutationResponse, ResponseErrorConfig<Error>, {slug: DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidPathParams["slug"], companyId: DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidPathParams["companyId"], employeeId: DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidPathParams["employeeId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidMutationKey()

  const baseOptions = deleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidMutationOptions(config) as UseMutationOptions<DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidMutationResponse, ResponseErrorConfig<Error>, {slug: DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidPathParams["slug"], companyId: DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidPathParams["companyId"], employeeId: DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidPathParams["employeeId"]}, TContext>


  return useMutation<DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidMutationResponse, ResponseErrorConfig<Error>, {slug: DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidPathParams["slug"], companyId: DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidPathParams["companyId"], employeeId: DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidPathParams["employeeId"]}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidMutationResponse, ResponseErrorConfig<Error>, {slug: DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidPathParams["slug"], companyId: DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidPathParams["companyId"], employeeId: DeleteOrganizationsSlugCompaniesCompanyidEmployeesEmployeeidPathParams["employeeId"]}, TContext>
}