/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { GetOrganizationsSlugMembershipQueryResponse, GetOrganizationsSlugMembershipPathParams } from "../types/GetOrganizationsSlugMembership.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getOrganizationsSlugMembershipQueryKey = ({ slug }: { slug: GetOrganizationsSlugMembershipPathParams["slug"] }) => [{ url: '/organizations/:slug/membership', params: {slug:slug} }] as const

export type GetOrganizationsSlugMembershipQueryKey = ReturnType<typeof getOrganizationsSlugMembershipQueryKey>

/**
 * @summary Get Organization Membership
 * {@link /organizations/:slug/membership}
 */
export async function getOrganizationsSlugMembership({ slug }: { slug: GetOrganizationsSlugMembershipPathParams["slug"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetOrganizationsSlugMembershipQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/organizations/${slug}/membership`, ... requestConfig })  
  return res.data
}

export function getOrganizationsSlugMembershipQueryOptions({ slug }: { slug: GetOrganizationsSlugMembershipPathParams["slug"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getOrganizationsSlugMembershipQueryKey({ slug })
  return queryOptions<GetOrganizationsSlugMembershipQueryResponse, ResponseErrorConfig<Error>, GetOrganizationsSlugMembershipQueryResponse, typeof queryKey>({
   enabled: !!(slug),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getOrganizationsSlugMembership({ slug }, config)
   },
  })
}

/**
 * @summary Get Organization Membership
 * {@link /organizations/:slug/membership}
 */
export function useGetOrganizationsSlugMembership<TData = GetOrganizationsSlugMembershipQueryResponse, TQueryData = GetOrganizationsSlugMembershipQueryResponse, TQueryKey extends QueryKey = GetOrganizationsSlugMembershipQueryKey>({ slug }: { slug: GetOrganizationsSlugMembershipPathParams["slug"] }, options: 
{
  query?: Partial<QueryObserverOptions<GetOrganizationsSlugMembershipQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getOrganizationsSlugMembershipQueryKey({ slug })


  const query = useQuery({
   ...getOrganizationsSlugMembershipQueryOptions({ slug }, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}