/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { GetOrganizationsQueryResponse } from "../types/GetOrganizations.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getOrganizationsQueryKey = () => [{ url: '/organizations' }] as const

export type GetOrganizationsQueryKey = ReturnType<typeof getOrganizationsQueryKey>

/**
 * @summary Get Organizations
 * {@link /organizations}
 */
export async function getOrganizations(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetOrganizationsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/organizations`, ... requestConfig })  
  return res.data
}

export function getOrganizationsQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getOrganizationsQueryKey()
  return queryOptions<GetOrganizationsQueryResponse, ResponseErrorConfig<Error>, GetOrganizationsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getOrganizations(config)
   },
  })
}

/**
 * @summary Get Organizations
 * {@link /organizations}
 */
export function useGetOrganizations<TData = GetOrganizationsQueryResponse, TQueryData = GetOrganizationsQueryResponse, TQueryKey extends QueryKey = GetOrganizationsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetOrganizationsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getOrganizationsQueryKey()


  const query = useQuery({
   ...getOrganizationsQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}