/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { GetProfileQueryResponse } from "../types/GetProfile.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getProfileSuspenseQueryKey = () => [{ url: '/profile' }] as const

export type GetProfileSuspenseQueryKey = ReturnType<typeof getProfileSuspenseQueryKey>

/**
 * @summary Get current user's profile
 * {@link /profile}
 */
export async function getProfileSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetProfileQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/profile`, ... requestConfig })  
  return res.data
}

export function getProfileSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getProfileSuspenseQueryKey()
  return queryOptions<GetProfileQueryResponse, ResponseErrorConfig<Error>, GetProfileQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getProfileSuspense(config)
   },
  })
}

/**
 * @summary Get current user's profile
 * {@link /profile}
 */
export function useGetProfileSuspense<TData = GetProfileQueryResponse, TQueryKey extends QueryKey = GetProfileSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetProfileQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getProfileSuspenseQueryKey()


  const query = useSuspenseQuery({
   ...getProfileSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}