/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { GetOrganizationsSlugCompaniesQueryResponse, GetOrganizationsSlugCompaniesPathParams } from "../types/GetOrganizationsSlugCompanies.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getOrganizationsSlugCompaniesQueryKey = ({ slug }: { slug: GetOrganizationsSlugCompaniesPathParams["slug"] }) => [{ url: '/organizations/:slug/companies', params: {slug:slug} }] as const

export type GetOrganizationsSlugCompaniesQueryKey = ReturnType<typeof getOrganizationsSlugCompaniesQueryKey>

/**
 * @summary Get companies
 * {@link /organizations/:slug/companies}
 */
export async function getOrganizationsSlugCompanies({ slug }: { slug: GetOrganizationsSlugCompaniesPathParams["slug"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetOrganizationsSlugCompaniesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/organizations/${slug}/companies`, ... requestConfig })  
  return res.data
}

export function getOrganizationsSlugCompaniesQueryOptions({ slug }: { slug: GetOrganizationsSlugCompaniesPathParams["slug"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getOrganizationsSlugCompaniesQueryKey({ slug })
  return queryOptions<GetOrganizationsSlugCompaniesQueryResponse, ResponseErrorConfig<Error>, GetOrganizationsSlugCompaniesQueryResponse, typeof queryKey>({
   enabled: !!(slug),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getOrganizationsSlugCompanies({ slug }, config)
   },
  })
}

/**
 * @summary Get companies
 * {@link /organizations/:slug/companies}
 */
export function useGetOrganizationsSlugCompanies<TData = GetOrganizationsSlugCompaniesQueryResponse, TQueryData = GetOrganizationsSlugCompaniesQueryResponse, TQueryKey extends QueryKey = GetOrganizationsSlugCompaniesQueryKey>({ slug }: { slug: GetOrganizationsSlugCompaniesPathParams["slug"] }, options: 
{
  query?: Partial<QueryObserverOptions<GetOrganizationsSlugCompaniesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getOrganizationsSlugCompaniesQueryKey({ slug })


  const query = useQuery({
   ...getOrganizationsSlugCompaniesQueryOptions({ slug }, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}