/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { GetPendingInvitesQueryResponse } from "../types/GetPendingInvites.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getPendingInvitesSuspenseQueryKey = () => [{ url: '/pending-invites' }] as const

export type GetPendingInvitesSuspenseQueryKey = ReturnType<typeof getPendingInvitesSuspenseQueryKey>

/**
 * @summary Get all user pending invites
 * {@link /pending-invites}
 */
export async function getPendingInvitesSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetPendingInvitesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/pending-invites`, ... requestConfig })  
  return res.data
}

export function getPendingInvitesSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getPendingInvitesSuspenseQueryKey()
  return queryOptions<GetPendingInvitesQueryResponse, ResponseErrorConfig<Error>, GetPendingInvitesQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getPendingInvitesSuspense(config)
   },
  })
}

/**
 * @summary Get all user pending invites
 * {@link /pending-invites}
 */
export function useGetPendingInvitesSuspense<TData = GetPendingInvitesQueryResponse, TQueryKey extends QueryKey = GetPendingInvitesSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetPendingInvitesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getPendingInvitesSuspenseQueryKey()


  const query = useSuspenseQuery({
   ...getPendingInvitesSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}