/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { PostPasswordResetMutationRequest, PostPasswordResetMutationResponse } from "../types/PostPasswordReset.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postPasswordResetMutationKey = () => [{ url: '/password/reset' }] as const

export type PostPasswordResetMutationKey = ReturnType<typeof postPasswordResetMutationKey>

/**
 * @summary Reset user password
 * {@link /password/reset}
 */
export async function postPasswordReset({ data }: { data: PostPasswordResetMutationRequest }, config: Partial<RequestConfig<PostPasswordResetMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostPasswordResetMutationResponse, ResponseErrorConfig<Error>, PostPasswordResetMutationRequest>({ method : "POST", url : `/password/reset`, data : requestData, ... requestConfig })  
  return res.data
}

export function postPasswordResetMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostPasswordResetMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postPasswordResetMutationKey()
  return mutationOptions<PostPasswordResetMutationResponse, ResponseErrorConfig<Error>, {data: PostPasswordResetMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postPasswordReset({ data }, config)
    },
  })
}

/**
 * @summary Reset user password
 * {@link /password/reset}
 */
export function usePostPasswordReset<TContext>(options: 
{
  mutation?: UseMutationOptions<PostPasswordResetMutationResponse, ResponseErrorConfig<Error>, {data: PostPasswordResetMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostPasswordResetMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postPasswordResetMutationKey()

  const baseOptions = postPasswordResetMutationOptions(config) as UseMutationOptions<PostPasswordResetMutationResponse, ResponseErrorConfig<Error>, {data: PostPasswordResetMutationRequest}, TContext>


  return useMutation<PostPasswordResetMutationResponse, ResponseErrorConfig<Error>, {data: PostPasswordResetMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PostPasswordResetMutationResponse, ResponseErrorConfig<Error>, {data: PostPasswordResetMutationRequest}, TContext>
}