/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { PutOrganizationsSlugMembersMemberidMutationRequest, PutOrganizationsSlugMembersMemberidMutationResponse, PutOrganizationsSlugMembersMemberidPathParams } from "../types/PutOrganizationsSlugMembersMemberid.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const putOrganizationsSlugMembersMemberidMutationKey = () => [{ url: '/organizations/:slug/members/:memberId' }] as const

export type PutOrganizationsSlugMembersMemberidMutationKey = ReturnType<typeof putOrganizationsSlugMembersMemberidMutationKey>

/**
 * @summary Update a member
 * {@link /organizations/:slug/members/:memberId}
 */
export async function putOrganizationsSlugMembersMemberid({ slug, memberId, data }: { slug: PutOrganizationsSlugMembersMemberidPathParams["slug"]; memberId: PutOrganizationsSlugMembersMemberidPathParams["memberId"]; data: PutOrganizationsSlugMembersMemberidMutationRequest }, config: Partial<RequestConfig<PutOrganizationsSlugMembersMemberidMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PutOrganizationsSlugMembersMemberidMutationResponse, ResponseErrorConfig<Error>, PutOrganizationsSlugMembersMemberidMutationRequest>({ method : "PUT", url : `/organizations/${slug}/members/${memberId}`, data : requestData, ... requestConfig })  
  return res.data
}

export function putOrganizationsSlugMembersMemberidMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PutOrganizationsSlugMembersMemberidMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = putOrganizationsSlugMembersMemberidMutationKey()
  return mutationOptions<PutOrganizationsSlugMembersMemberidMutationResponse, ResponseErrorConfig<Error>, {slug: PutOrganizationsSlugMembersMemberidPathParams["slug"], memberId: PutOrganizationsSlugMembersMemberidPathParams["memberId"], data: PutOrganizationsSlugMembersMemberidMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ slug, memberId, data }) => {
      return putOrganizationsSlugMembersMemberid({ slug, memberId, data }, config)
    },
  })
}

/**
 * @summary Update a member
 * {@link /organizations/:slug/members/:memberId}
 */
export function usePutOrganizationsSlugMembersMemberid<TContext>(options: 
{
  mutation?: UseMutationOptions<PutOrganizationsSlugMembersMemberidMutationResponse, ResponseErrorConfig<Error>, {slug: PutOrganizationsSlugMembersMemberidPathParams["slug"], memberId: PutOrganizationsSlugMembersMemberidPathParams["memberId"], data: PutOrganizationsSlugMembersMemberidMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PutOrganizationsSlugMembersMemberidMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? putOrganizationsSlugMembersMemberidMutationKey()

  const baseOptions = putOrganizationsSlugMembersMemberidMutationOptions(config) as UseMutationOptions<PutOrganizationsSlugMembersMemberidMutationResponse, ResponseErrorConfig<Error>, {slug: PutOrganizationsSlugMembersMemberidPathParams["slug"], memberId: PutOrganizationsSlugMembersMemberidPathParams["memberId"], data: PutOrganizationsSlugMembersMemberidMutationRequest}, TContext>


  return useMutation<PutOrganizationsSlugMembersMemberidMutationResponse, ResponseErrorConfig<Error>, {slug: PutOrganizationsSlugMembersMemberidPathParams["slug"], memberId: PutOrganizationsSlugMembersMemberidPathParams["memberId"], data: PutOrganizationsSlugMembersMemberidMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PutOrganizationsSlugMembersMemberidMutationResponse, ResponseErrorConfig<Error>, {slug: PutOrganizationsSlugMembersMemberidPathParams["slug"], memberId: PutOrganizationsSlugMembersMemberidPathParams["memberId"], data: PutOrganizationsSlugMembersMemberidMutationRequest}, TContext>
}