/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { PutOrganizationsSlugCategoriesIdMutationRequest, PutOrganizationsSlugCategoriesIdMutationResponse, PutOrganizationsSlugCategoriesIdPathParams } from "../types/PutOrganizationsSlugCategoriesId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const putOrganizationsSlugCategoriesIdMutationKey = () => [{ url: '/organizations/:slug/categories/:id' }] as const

export type PutOrganizationsSlugCategoriesIdMutationKey = ReturnType<typeof putOrganizationsSlugCategoriesIdMutationKey>

/**
 * @summary Update category
 * {@link /organizations/:slug/categories/:id}
 */
export async function putOrganizationsSlugCategoriesId({ slug, id, data }: { slug: PutOrganizationsSlugCategoriesIdPathParams["slug"]; id: PutOrganizationsSlugCategoriesIdPathParams["id"]; data: PutOrganizationsSlugCategoriesIdMutationRequest }, config: Partial<RequestConfig<PutOrganizationsSlugCategoriesIdMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PutOrganizationsSlugCategoriesIdMutationResponse, ResponseErrorConfig<Error>, PutOrganizationsSlugCategoriesIdMutationRequest>({ method : "PUT", url : `/organizations/${slug}/categories/${id}`, data : requestData, ... requestConfig })  
  return res.data
}

export function putOrganizationsSlugCategoriesIdMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PutOrganizationsSlugCategoriesIdMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = putOrganizationsSlugCategoriesIdMutationKey()
  return mutationOptions<PutOrganizationsSlugCategoriesIdMutationResponse, ResponseErrorConfig<Error>, {slug: PutOrganizationsSlugCategoriesIdPathParams["slug"], id: PutOrganizationsSlugCategoriesIdPathParams["id"], data: PutOrganizationsSlugCategoriesIdMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ slug, id, data }) => {
      return putOrganizationsSlugCategoriesId({ slug, id, data }, config)
    },
  })
}

/**
 * @summary Update category
 * {@link /organizations/:slug/categories/:id}
 */
export function usePutOrganizationsSlugCategoriesId<TContext>(options: 
{
  mutation?: UseMutationOptions<PutOrganizationsSlugCategoriesIdMutationResponse, ResponseErrorConfig<Error>, {slug: PutOrganizationsSlugCategoriesIdPathParams["slug"], id: PutOrganizationsSlugCategoriesIdPathParams["id"], data: PutOrganizationsSlugCategoriesIdMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PutOrganizationsSlugCategoriesIdMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? putOrganizationsSlugCategoriesIdMutationKey()

  const baseOptions = putOrganizationsSlugCategoriesIdMutationOptions(config) as UseMutationOptions<PutOrganizationsSlugCategoriesIdMutationResponse, ResponseErrorConfig<Error>, {slug: PutOrganizationsSlugCategoriesIdPathParams["slug"], id: PutOrganizationsSlugCategoriesIdPathParams["id"], data: PutOrganizationsSlugCategoriesIdMutationRequest}, TContext>


  return useMutation<PutOrganizationsSlugCategoriesIdMutationResponse, ResponseErrorConfig<Error>, {slug: PutOrganizationsSlugCategoriesIdPathParams["slug"], id: PutOrganizationsSlugCategoriesIdPathParams["id"], data: PutOrganizationsSlugCategoriesIdMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PutOrganizationsSlugCategoriesIdMutationResponse, ResponseErrorConfig<Error>, {slug: PutOrganizationsSlugCategoriesIdPathParams["slug"], id: PutOrganizationsSlugCategoriesIdPathParams["id"], data: PutOrganizationsSlugCategoriesIdMutationRequest}, TContext>
}