/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { PostOrganizationsSlugInvitesMutationRequest, PostOrganizationsSlugInvitesMutationResponse, PostOrganizationsSlugInvitesPathParams } from "../types/PostOrganizationsSlugInvites.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postOrganizationsSlugInvitesMutationKey = () => [{ url: '/organizations/:slug/invites' }] as const

export type PostOrganizationsSlugInvitesMutationKey = ReturnType<typeof postOrganizationsSlugInvitesMutationKey>

/**
 * @summary Create an invite for an organization
 * {@link /organizations/:slug/invites}
 */
export async function postOrganizationsSlugInvites({ slug, data }: { slug: PostOrganizationsSlugInvitesPathParams["slug"]; data: PostOrganizationsSlugInvitesMutationRequest }, config: Partial<RequestConfig<PostOrganizationsSlugInvitesMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostOrganizationsSlugInvitesMutationResponse, ResponseErrorConfig<Error>, PostOrganizationsSlugInvitesMutationRequest>({ method : "POST", url : `/organizations/${slug}/invites`, data : requestData, ... requestConfig })  
  return res.data
}

export function postOrganizationsSlugInvitesMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostOrganizationsSlugInvitesMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postOrganizationsSlugInvitesMutationKey()
  return mutationOptions<PostOrganizationsSlugInvitesMutationResponse, ResponseErrorConfig<Error>, {slug: PostOrganizationsSlugInvitesPathParams["slug"], data: PostOrganizationsSlugInvitesMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ slug, data }) => {
      return postOrganizationsSlugInvites({ slug, data }, config)
    },
  })
}

/**
 * @summary Create an invite for an organization
 * {@link /organizations/:slug/invites}
 */
export function usePostOrganizationsSlugInvites<TContext>(options: 
{
  mutation?: UseMutationOptions<PostOrganizationsSlugInvitesMutationResponse, ResponseErrorConfig<Error>, {slug: PostOrganizationsSlugInvitesPathParams["slug"], data: PostOrganizationsSlugInvitesMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostOrganizationsSlugInvitesMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postOrganizationsSlugInvitesMutationKey()

  const baseOptions = postOrganizationsSlugInvitesMutationOptions(config) as UseMutationOptions<PostOrganizationsSlugInvitesMutationResponse, ResponseErrorConfig<Error>, {slug: PostOrganizationsSlugInvitesPathParams["slug"], data: PostOrganizationsSlugInvitesMutationRequest}, TContext>


  return useMutation<PostOrganizationsSlugInvitesMutationResponse, ResponseErrorConfig<Error>, {slug: PostOrganizationsSlugInvitesPathParams["slug"], data: PostOrganizationsSlugInvitesMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PostOrganizationsSlugInvitesMutationResponse, ResponseErrorConfig<Error>, {slug: PostOrganizationsSlugInvitesPathParams["slug"], data: PostOrganizationsSlugInvitesMutationRequest}, TContext>
}