/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { PostPasswordRecoverMutationRequest, PostPasswordRecoverMutationResponse } from "../types/PostPasswordRecover.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postPasswordRecoverMutationKey = () => [{ url: '/password/recover' }] as const

export type PostPasswordRecoverMutationKey = ReturnType<typeof postPasswordRecoverMutationKey>

/**
 * @summary Request password recovery
 * {@link /password/recover}
 */
export async function postPasswordRecover({ data }: { data: PostPasswordRecoverMutationRequest }, config: Partial<RequestConfig<PostPasswordRecoverMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostPasswordRecoverMutationResponse, ResponseErrorConfig<Error>, PostPasswordRecoverMutationRequest>({ method : "POST", url : `/password/recover`, data : requestData, ... requestConfig })  
  return res.data
}

export function postPasswordRecoverMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostPasswordRecoverMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postPasswordRecoverMutationKey()
  return mutationOptions<PostPasswordRecoverMutationResponse, ResponseErrorConfig<Error>, {data: PostPasswordRecoverMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postPasswordRecover({ data }, config)
    },
  })
}

/**
 * @summary Request password recovery
 * {@link /password/recover}
 */
export function usePostPasswordRecover<TContext>(options: 
{
  mutation?: UseMutationOptions<PostPasswordRecoverMutationResponse, ResponseErrorConfig<Error>, {data: PostPasswordRecoverMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostPasswordRecoverMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postPasswordRecoverMutationKey()

  const baseOptions = postPasswordRecoverMutationOptions(config) as UseMutationOptions<PostPasswordRecoverMutationResponse, ResponseErrorConfig<Error>, {data: PostPasswordRecoverMutationRequest}, TContext>


  return useMutation<PostPasswordRecoverMutationResponse, ResponseErrorConfig<Error>, {data: PostPasswordRecoverMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PostPasswordRecoverMutationResponse, ResponseErrorConfig<Error>, {data: PostPasswordRecoverMutationRequest}, TContext>
}