/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { PatchOrganizationsSlugCostcentersCostcenteridMutationRequest, PatchOrganizationsSlugCostcentersCostcenteridMutationResponse, PatchOrganizationsSlugCostcentersCostcenteridPathParams } from "../types/PatchOrganizationsSlugCostcentersCostcenterid.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const patchOrganizationsSlugCostcentersCostcenteridMutationKey = () => [{ url: '/organizations/:slug/costCenters/:costCenterId' }] as const

export type PatchOrganizationsSlugCostcentersCostcenteridMutationKey = ReturnType<typeof patchOrganizationsSlugCostcentersCostcenteridMutationKey>

/**
 * @summary Update cost center
 * {@link /organizations/:slug/costCenters/:costCenterId}
 */
export async function patchOrganizationsSlugCostcentersCostcenterid({ slug, costCenterId, data }: { slug: PatchOrganizationsSlugCostcentersCostcenteridPathParams["slug"]; costCenterId: PatchOrganizationsSlugCostcentersCostcenteridPathParams["costCenterId"]; data: PatchOrganizationsSlugCostcentersCostcenteridMutationRequest }, config: Partial<RequestConfig<PatchOrganizationsSlugCostcentersCostcenteridMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PatchOrganizationsSlugCostcentersCostcenteridMutationResponse, ResponseErrorConfig<Error>, PatchOrganizationsSlugCostcentersCostcenteridMutationRequest>({ method : "PATCH", url : `/organizations/${slug}/costCenters/${costCenterId}`, data : requestData, ... requestConfig })  
  return res.data
}

export function patchOrganizationsSlugCostcentersCostcenteridMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PatchOrganizationsSlugCostcentersCostcenteridMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = patchOrganizationsSlugCostcentersCostcenteridMutationKey()
  return mutationOptions<PatchOrganizationsSlugCostcentersCostcenteridMutationResponse, ResponseErrorConfig<Error>, {slug: PatchOrganizationsSlugCostcentersCostcenteridPathParams["slug"], costCenterId: PatchOrganizationsSlugCostcentersCostcenteridPathParams["costCenterId"], data: PatchOrganizationsSlugCostcentersCostcenteridMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ slug, costCenterId, data }) => {
      return patchOrganizationsSlugCostcentersCostcenterid({ slug, costCenterId, data }, config)
    },
  })
}

/**
 * @summary Update cost center
 * {@link /organizations/:slug/costCenters/:costCenterId}
 */
export function usePatchOrganizationsSlugCostcentersCostcenterid<TContext>(options: 
{
  mutation?: UseMutationOptions<PatchOrganizationsSlugCostcentersCostcenteridMutationResponse, ResponseErrorConfig<Error>, {slug: PatchOrganizationsSlugCostcentersCostcenteridPathParams["slug"], costCenterId: PatchOrganizationsSlugCostcentersCostcenteridPathParams["costCenterId"], data: PatchOrganizationsSlugCostcentersCostcenteridMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PatchOrganizationsSlugCostcentersCostcenteridMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? patchOrganizationsSlugCostcentersCostcenteridMutationKey()

  const baseOptions = patchOrganizationsSlugCostcentersCostcenteridMutationOptions(config) as UseMutationOptions<PatchOrganizationsSlugCostcentersCostcenteridMutationResponse, ResponseErrorConfig<Error>, {slug: PatchOrganizationsSlugCostcentersCostcenteridPathParams["slug"], costCenterId: PatchOrganizationsSlugCostcentersCostcenteridPathParams["costCenterId"], data: PatchOrganizationsSlugCostcentersCostcenteridMutationRequest}, TContext>


  return useMutation<PatchOrganizationsSlugCostcentersCostcenteridMutationResponse, ResponseErrorConfig<Error>, {slug: PatchOrganizationsSlugCostcentersCostcenteridPathParams["slug"], costCenterId: PatchOrganizationsSlugCostcentersCostcenteridPathParams["costCenterId"], data: PatchOrganizationsSlugCostcentersCostcenteridMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PatchOrganizationsSlugCostcentersCostcenteridMutationResponse, ResponseErrorConfig<Error>, {slug: PatchOrganizationsSlugCostcentersCostcenteridPathParams["slug"], costCenterId: PatchOrganizationsSlugCostcentersCostcenteridPathParams["costCenterId"], data: PatchOrganizationsSlugCostcentersCostcenteridMutationRequest}, TContext>
}