/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { PutOrganizationSlugMutationRequest, PutOrganizationSlugMutationResponse, PutOrganizationSlugPathParams } from "../types/PutOrganizationSlug.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const putOrganizationSlugMutationKey = () => [{ url: '/organization/:slug' }] as const

export type PutOrganizationSlugMutationKey = ReturnType<typeof putOrganizationSlugMutationKey>

/**
 * @summary Update an organization
 * {@link /organization/:slug}
 */
export async function putOrganizationSlug({ slug, data }: { slug: PutOrganizationSlugPathParams["slug"]; data: PutOrganizationSlugMutationRequest }, config: Partial<RequestConfig<PutOrganizationSlugMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PutOrganizationSlugMutationResponse, ResponseErrorConfig<Error>, PutOrganizationSlugMutationRequest>({ method : "PUT", url : `/organization/${slug}`, data : requestData, ... requestConfig })  
  return res.data
}

export function putOrganizationSlugMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PutOrganizationSlugMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = putOrganizationSlugMutationKey()
  return mutationOptions<PutOrganizationSlugMutationResponse, ResponseErrorConfig<Error>, {slug: PutOrganizationSlugPathParams["slug"], data: PutOrganizationSlugMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ slug, data }) => {
      return putOrganizationSlug({ slug, data }, config)
    },
  })
}

/**
 * @summary Update an organization
 * {@link /organization/:slug}
 */
export function usePutOrganizationSlug<TContext>(options: 
{
  mutation?: UseMutationOptions<PutOrganizationSlugMutationResponse, ResponseErrorConfig<Error>, {slug: PutOrganizationSlugPathParams["slug"], data: PutOrganizationSlugMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PutOrganizationSlugMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? putOrganizationSlugMutationKey()

  const baseOptions = putOrganizationSlugMutationOptions(config) as UseMutationOptions<PutOrganizationSlugMutationResponse, ResponseErrorConfig<Error>, {slug: PutOrganizationSlugPathParams["slug"], data: PutOrganizationSlugMutationRequest}, TContext>


  return useMutation<PutOrganizationSlugMutationResponse, ResponseErrorConfig<Error>, {slug: PutOrganizationSlugPathParams["slug"], data: PutOrganizationSlugMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PutOrganizationSlugMutationResponse, ResponseErrorConfig<Error>, {slug: PutOrganizationSlugPathParams["slug"], data: PutOrganizationSlugMutationRequest}, TContext>
}