/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { PostOrganizationsMutationRequest, PostOrganizationsMutationResponse } from "../types/PostOrganizations.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postOrganizationsMutationKey = () => [{ url: '/organizations' }] as const

export type PostOrganizationsMutationKey = ReturnType<typeof postOrganizationsMutationKey>

/**
 * @summary Create a new organization
 * {@link /organizations}
 */
export async function postOrganizations({ data }: { data: PostOrganizationsMutationRequest }, config: Partial<RequestConfig<PostOrganizationsMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostOrganizationsMutationResponse, ResponseErrorConfig<Error>, PostOrganizationsMutationRequest>({ method : "POST", url : `/organizations`, data : requestData, ... requestConfig })  
  return res.data
}

export function postOrganizationsMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostOrganizationsMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postOrganizationsMutationKey()
  return mutationOptions<PostOrganizationsMutationResponse, ResponseErrorConfig<Error>, {data: PostOrganizationsMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postOrganizations({ data }, config)
    },
  })
}

/**
 * @summary Create a new organization
 * {@link /organizations}
 */
export function usePostOrganizations<TContext>(options: 
{
  mutation?: UseMutationOptions<PostOrganizationsMutationResponse, ResponseErrorConfig<Error>, {data: PostOrganizationsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostOrganizationsMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postOrganizationsMutationKey()

  const baseOptions = postOrganizationsMutationOptions(config) as UseMutationOptions<PostOrganizationsMutationResponse, ResponseErrorConfig<Error>, {data: PostOrganizationsMutationRequest}, TContext>


  return useMutation<PostOrganizationsMutationResponse, ResponseErrorConfig<Error>, {data: PostOrganizationsMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PostOrganizationsMutationResponse, ResponseErrorConfig<Error>, {data: PostOrganizationsMutationRequest}, TContext>
}