/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { PostOrganizationsSlugCompaniesCompanyidEmployeesMutationRequest, PostOrganizationsSlugCompaniesCompanyidEmployeesMutationResponse, PostOrganizationsSlugCompaniesCompanyidEmployeesPathParams } from "../types/PostOrganizationsSlugCompaniesCompanyidEmployees.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postOrganizationsSlugCompaniesCompanyidEmployeesMutationKey = () => [{ url: '/organizations/:slug/companies/:companyId/employees' }] as const

export type PostOrganizationsSlugCompaniesCompanyidEmployeesMutationKey = ReturnType<typeof postOrganizationsSlugCompaniesCompanyidEmployeesMutationKey>

/**
 * @summary Create a new employee
 * {@link /organizations/:slug/companies/:companyId/employees}
 */
export async function postOrganizationsSlugCompaniesCompanyidEmployees({ slug, companyId, data }: { slug: PostOrganizationsSlugCompaniesCompanyidEmployeesPathParams["slug"]; companyId: PostOrganizationsSlugCompaniesCompanyidEmployeesPathParams["companyId"]; data: PostOrganizationsSlugCompaniesCompanyidEmployeesMutationRequest }, config: Partial<RequestConfig<PostOrganizationsSlugCompaniesCompanyidEmployeesMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostOrganizationsSlugCompaniesCompanyidEmployeesMutationResponse, ResponseErrorConfig<Error>, PostOrganizationsSlugCompaniesCompanyidEmployeesMutationRequest>({ method : "POST", url : `/organizations/${slug}/companies/${companyId}/employees`, data : requestData, ... requestConfig })  
  return res.data
}

export function postOrganizationsSlugCompaniesCompanyidEmployeesMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostOrganizationsSlugCompaniesCompanyidEmployeesMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postOrganizationsSlugCompaniesCompanyidEmployeesMutationKey()
  return mutationOptions<PostOrganizationsSlugCompaniesCompanyidEmployeesMutationResponse, ResponseErrorConfig<Error>, {slug: PostOrganizationsSlugCompaniesCompanyidEmployeesPathParams["slug"], companyId: PostOrganizationsSlugCompaniesCompanyidEmployeesPathParams["companyId"], data: PostOrganizationsSlugCompaniesCompanyidEmployeesMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ slug, companyId, data }) => {
      return postOrganizationsSlugCompaniesCompanyidEmployees({ slug, companyId, data }, config)
    },
  })
}

/**
 * @summary Create a new employee
 * {@link /organizations/:slug/companies/:companyId/employees}
 */
export function usePostOrganizationsSlugCompaniesCompanyidEmployees<TContext>(options: 
{
  mutation?: UseMutationOptions<PostOrganizationsSlugCompaniesCompanyidEmployeesMutationResponse, ResponseErrorConfig<Error>, {slug: PostOrganizationsSlugCompaniesCompanyidEmployeesPathParams["slug"], companyId: PostOrganizationsSlugCompaniesCompanyidEmployeesPathParams["companyId"], data: PostOrganizationsSlugCompaniesCompanyidEmployeesMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostOrganizationsSlugCompaniesCompanyidEmployeesMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postOrganizationsSlugCompaniesCompanyidEmployeesMutationKey()

  const baseOptions = postOrganizationsSlugCompaniesCompanyidEmployeesMutationOptions(config) as UseMutationOptions<PostOrganizationsSlugCompaniesCompanyidEmployeesMutationResponse, ResponseErrorConfig<Error>, {slug: PostOrganizationsSlugCompaniesCompanyidEmployeesPathParams["slug"], companyId: PostOrganizationsSlugCompaniesCompanyidEmployeesPathParams["companyId"], data: PostOrganizationsSlugCompaniesCompanyidEmployeesMutationRequest}, TContext>


  return useMutation<PostOrganizationsSlugCompaniesCompanyidEmployeesMutationResponse, ResponseErrorConfig<Error>, {slug: PostOrganizationsSlugCompaniesCompanyidEmployeesPathParams["slug"], companyId: PostOrganizationsSlugCompaniesCompanyidEmployeesPathParams["companyId"], data: PostOrganizationsSlugCompaniesCompanyidEmployeesMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PostOrganizationsSlugCompaniesCompanyidEmployeesMutationResponse, ResponseErrorConfig<Error>, {slug: PostOrganizationsSlugCompaniesCompanyidEmployeesPathParams["slug"], companyId: PostOrganizationsSlugCompaniesCompanyidEmployeesPathParams["companyId"], data: PostOrganizationsSlugCompaniesCompanyidEmployeesMutationRequest}, TContext>
}