/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { PostInvitesInviteidAcceptMutationResponse, PostInvitesInviteidAcceptPathParams } from "../types/PostInvitesInviteidAccept.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postInvitesInviteidAcceptMutationKey = () => [{ url: '/invites/:inviteId/accept' }] as const

export type PostInvitesInviteidAcceptMutationKey = ReturnType<typeof postInvitesInviteidAcceptMutationKey>

/**
 * @summary Accept an invite
 * {@link /invites/:inviteId/accept}
 */
export async function postInvitesInviteidAccept({ inviteId }: { inviteId: PostInvitesInviteidAcceptPathParams["inviteId"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<PostInvitesInviteidAcceptMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : `/invites/${inviteId}/accept`, ... requestConfig })  
  return res.data
}

export function postInvitesInviteidAcceptMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = postInvitesInviteidAcceptMutationKey()
  return mutationOptions<PostInvitesInviteidAcceptMutationResponse, ResponseErrorConfig<Error>, {inviteId: PostInvitesInviteidAcceptPathParams["inviteId"]}, TContext>({
    mutationKey,
    mutationFn: async({ inviteId }) => {
      return postInvitesInviteidAccept({ inviteId }, config)
    },
  })
}

/**
 * @summary Accept an invite
 * {@link /invites/:inviteId/accept}
 */
export function usePostInvitesInviteidAccept<TContext>(options: 
{
  mutation?: UseMutationOptions<PostInvitesInviteidAcceptMutationResponse, ResponseErrorConfig<Error>, {inviteId: PostInvitesInviteidAcceptPathParams["inviteId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postInvitesInviteidAcceptMutationKey()

  const baseOptions = postInvitesInviteidAcceptMutationOptions(config) as UseMutationOptions<PostInvitesInviteidAcceptMutationResponse, ResponseErrorConfig<Error>, {inviteId: PostInvitesInviteidAcceptPathParams["inviteId"]}, TContext>


  return useMutation<PostInvitesInviteidAcceptMutationResponse, ResponseErrorConfig<Error>, {inviteId: PostInvitesInviteidAcceptPathParams["inviteId"]}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PostInvitesInviteidAcceptMutationResponse, ResponseErrorConfig<Error>, {inviteId: PostInvitesInviteidAcceptPathParams["inviteId"]}, TContext>
}