/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetOrganizationsSlugCompaniesCompanyidEmployeesPathParams = {
    /**
     * @type string
    */
    slug: string;
    /**
     * @type string, uuid
    */
    companyId: string;
};

/**
 * @description Default Response
*/
export type GetOrganizationsSlugCompaniesCompanyidEmployees200 = {
    /**
     * @type array
    */
    employees: {
        /**
         * @type string, uuid
        */
        id: string;
        /**
         * @type string
        */
        name: string;
        /**
         * @type string
        */
        department: string;
    }[];
};

export type GetOrganizationsSlugCompaniesCompanyidEmployeesQueryResponse = GetOrganizationsSlugCompaniesCompanyidEmployees200;

export type GetOrganizationsSlugCompaniesCompanyidEmployeesQuery = {
    Response: GetOrganizationsSlugCompaniesCompanyidEmployees200;
    PathParams: GetOrganizationsSlugCompaniesCompanyidEmployeesPathParams;
    Errors: any;
};