/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PatchOrganizationsSlugCompaniesCompanyidUnitsUnitidPathParams = {
    /**
     * @type string
    */
    slug: string;
    /**
     * @type string, uuid
    */
    companyId: string;
    /**
     * @type string, uuid
    */
    unitId: string;
};

export const patchOrganizationsSlugCompaniesCompanyidUnitsUnitid204Enum = {} as const;

export type PatchOrganizationsSlugCompaniesCompanyidUnitsUnitid204EnumKey = (typeof patchOrganizationsSlugCompaniesCompanyidUnitsUnitid204Enum)[keyof typeof patchOrganizationsSlugCompaniesCompanyidUnitsUnitid204Enum];

/**
 * @description Default Response
*/
export type PatchOrganizationsSlugCompaniesCompanyidUnitsUnitid204 = PatchOrganizationsSlugCompaniesCompanyidUnitsUnitid204EnumKey | null;

export type PatchOrganizationsSlugCompaniesCompanyidUnitsUnitidMutationRequest = {
    /**
     * @type string
    */
    name: string;
};

export type PatchOrganizationsSlugCompaniesCompanyidUnitsUnitidMutationResponse = PatchOrganizationsSlugCompaniesCompanyidUnitsUnitid204;

export type PatchOrganizationsSlugCompaniesCompanyidUnitsUnitidMutation = {
    Response: PatchOrganizationsSlugCompaniesCompanyidUnitsUnitid204;
    Request: PatchOrganizationsSlugCompaniesCompanyidUnitsUnitidMutationRequest;
    PathParams: PatchOrganizationsSlugCompaniesCompanyidUnitsUnitidPathParams;
    Errors: any;
};