/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PatchOrganizationsSlugCompaniesCompanyidPathParams = {
    /**
     * @type string
    */
    slug: string;
    /**
     * @type string, uuid
    */
    companyId: string;
};

export const patchOrganizationsSlugCompaniesCompanyid204Enum = {} as const;

export type PatchOrganizationsSlugCompaniesCompanyid204EnumKey = (typeof patchOrganizationsSlugCompaniesCompanyid204Enum)[keyof typeof patchOrganizationsSlugCompaniesCompanyid204Enum];

/**
 * @description Default Response
*/
export type PatchOrganizationsSlugCompaniesCompanyid204 = PatchOrganizationsSlugCompaniesCompanyid204EnumKey | null;

export type PatchOrganizationsSlugCompaniesCompanyidMutationRequest = {
    /**
     * @type string
    */
    name: string;
};

export type PatchOrganizationsSlugCompaniesCompanyidMutationResponse = PatchOrganizationsSlugCompaniesCompanyid204;

export type PatchOrganizationsSlugCompaniesCompanyidMutation = {
    Response: PatchOrganizationsSlugCompaniesCompanyid204;
    Request: PatchOrganizationsSlugCompaniesCompanyidMutationRequest;
    PathParams: PatchOrganizationsSlugCompaniesCompanyidPathParams;
    Errors: any;
};